### ISSUE TITLE
Single click on Menue Item should open/close it (inverting current setting)

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins.github.io#1]

**Comment by Gateway85** [comment]
I just read, that this was planned. Right now it does not work. I can open and close the menue item, but if I want to reopen it again it does not do so. 

Double-click does, but user experience is better with one click, consistently.

**Comment by mahmed0715** [comment]
Done!
Now on single click the menu will toggle.

**Comment by Gateway85** [comment]
verified in production. This is working fine.
