### ISSUE TITLE
Allow scrolling in Menue

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins.github.io#10]
Right now it is not possible to reach all items, as the scrolling the menue on the left is not possible.

**Comment by mahmed0715** [comment]
Solved,
Scrolling can be done, all content on left menu is shown.

**Comment by Gateway85** [comment]
Scrolling possible - verified in production. 
![uploads/6004b499-2538-4351-85fa-961d694dd6ac/Screen Shot 2015-05-20 at 15.00.25.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6004b499-2538-4351-85fa-961d694dd6ac%2FScreen+Shot+2015-05-20+at+15.00.25.png)
