### ISSUE TITLE
Show subtopic in Menue

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins.github.io#11]
There are subtopics, if we would also highlight this in the Menue it would be better to read. --> additional they could be hidden away to make the whole menue fit into one page

**Comment by mahmed0715** [comment]
which subtopics are you talking about?
the only subtopics i can see is : Implementation Notes
can you pls let me know?

**Comment by mahmed0715** [comment]
enabled subtopics

**Comment by Gateway85** [comment]
done and verified
![uploads/1701385b-79df-4e4c-86bf-3a4bfa40e262/Screen Shot 2015-05-11 at 18.01.52.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1701385b-79df-4e4c-86bf-3a4bfa40e262%2FScreen+Shot+2015-05-11+at+18.01.52.png)

**Comment by Gateway85** [comment]
Verified in production 

![uploads/b7f3d45d-14a3-4467-bf63-5068782c9273/Screen Shot 2015-05-20 at 15.05.12.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb7f3d45d-14a3-4467-bf63-5068782c9273%2FScreen+Shot+2015-05-20+at+15.05.12.png)
